version: '3.7'

services:
  pcs-health-monitor:
    image: ${DOCKER_REGISTRY:-parusnik}/pcs/health-monitor:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/Pcs.Health.Monitor/Dockerfile
